<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SampleApp.Plugin</RootNamespace>
    <AssemblyName>SampleApp.Plugin</AssemblyName>
    <DebugType>portable</DebugType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
