<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Infrastructure.Collections</RootNamespace>
    <AssemblyName>Infrastructure.Collections</AssemblyName>
    <DebugType>portable</DebugType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>